import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const supremeFont = localFont({
  src: [
    {
      path: "../fonts/regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/bold.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-supreme",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${supremeFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
